# Local Development Configuration for IntelliJ IDEA
# This file contains the configuration for running services locally

server:
  port: 8081

spring:
  application:
    name: client-person-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: banking_user
    password: banking_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.banking.client: DEBUG
    org.springframework.web: DEBUG
